apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: nodejs
        image: node:16-alpine
        command: ["node", "-e"]
        args:
          - |
            const http = require('http');
            http.createServer((req, res) => {
              res.writeHead(200, {'Content-Type': 'text/plain'});
              res.end(' destination');
            }).listen(3000);
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort

