apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adad-jenkins-ingress
  namespace: adad-jenkins
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ing.ingressHost }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adad-jenkins-chart-v2
                port:
                  number: 8080

