apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:masters
      rolearn: "role is masked as is sensitive "
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: "role is masked as is sensitive"
      username: terraform
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
